/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.libms.common_events.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderPlacedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2109274988693872642L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderPlacedEvent\",\"namespace\":\"com.libms.common_events.event\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"bookName\",\"type\":\"string\"},{\"name\":\"userEmail\",\"type\":\"string\"},{\"name\":\"userFirstName\",\"type\":\"string\"},{\"name\":\"userLastName\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderPlacedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderPlacedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderPlacedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderPlacedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderPlacedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderPlacedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderPlacedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderPlacedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderPlacedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence orderId;
  private java.lang.CharSequence bookName;
  private java.lang.CharSequence userEmail;
  private java.lang.CharSequence userFirstName;
  private java.lang.CharSequence userLastName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderPlacedEvent() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param bookName The new value for bookName
   * @param userEmail The new value for userEmail
   * @param userFirstName The new value for userFirstName
   * @param userLastName The new value for userLastName
   */
  public OrderPlacedEvent(java.lang.CharSequence orderId, java.lang.CharSequence bookName, java.lang.CharSequence userEmail, java.lang.CharSequence userFirstName, java.lang.CharSequence userLastName) {
    this.orderId = orderId;
    this.bookName = bookName;
    this.userEmail = userEmail;
    this.userFirstName = userFirstName;
    this.userLastName = userLastName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return bookName;
    case 2: return userEmail;
    case 3: return userFirstName;
    case 4: return userLastName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.CharSequence)value$; break;
    case 1: bookName = (java.lang.CharSequence)value$; break;
    case 2: userEmail = (java.lang.CharSequence)value$; break;
    case 3: userFirstName = (java.lang.CharSequence)value$; break;
    case 4: userLastName = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.CharSequence getOrderId() {
    return orderId;
  }


  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.CharSequence value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'bookName' field.
   * @return The value of the 'bookName' field.
   */
  public java.lang.CharSequence getBookName() {
    return bookName;
  }


  /**
   * Sets the value of the 'bookName' field.
   * @param value the value to set.
   */
  public void setBookName(java.lang.CharSequence value) {
    this.bookName = value;
  }

  /**
   * Gets the value of the 'userEmail' field.
   * @return The value of the 'userEmail' field.
   */
  public java.lang.CharSequence getUserEmail() {
    return userEmail;
  }


  /**
   * Sets the value of the 'userEmail' field.
   * @param value the value to set.
   */
  public void setUserEmail(java.lang.CharSequence value) {
    this.userEmail = value;
  }

  /**
   * Gets the value of the 'userFirstName' field.
   * @return The value of the 'userFirstName' field.
   */
  public java.lang.CharSequence getUserFirstName() {
    return userFirstName;
  }


  /**
   * Sets the value of the 'userFirstName' field.
   * @param value the value to set.
   */
  public void setUserFirstName(java.lang.CharSequence value) {
    this.userFirstName = value;
  }

  /**
   * Gets the value of the 'userLastName' field.
   * @return The value of the 'userLastName' field.
   */
  public java.lang.CharSequence getUserLastName() {
    return userLastName;
  }


  /**
   * Sets the value of the 'userLastName' field.
   * @param value the value to set.
   */
  public void setUserLastName(java.lang.CharSequence value) {
    this.userLastName = value;
  }

  /**
   * Creates a new OrderPlacedEvent RecordBuilder.
   * @return A new OrderPlacedEvent RecordBuilder
   */
  public static com.libms.common_events.event.OrderPlacedEvent.Builder newBuilder() {
    return new com.libms.common_events.event.OrderPlacedEvent.Builder();
  }

  /**
   * Creates a new OrderPlacedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderPlacedEvent RecordBuilder
   */
  public static com.libms.common_events.event.OrderPlacedEvent.Builder newBuilder(com.libms.common_events.event.OrderPlacedEvent.Builder other) {
    if (other == null) {
      return new com.libms.common_events.event.OrderPlacedEvent.Builder();
    } else {
      return new com.libms.common_events.event.OrderPlacedEvent.Builder(other);
    }
  }

  /**
   * Creates a new OrderPlacedEvent RecordBuilder by copying an existing OrderPlacedEvent instance.
   * @param other The existing instance to copy.
   * @return A new OrderPlacedEvent RecordBuilder
   */
  public static com.libms.common_events.event.OrderPlacedEvent.Builder newBuilder(com.libms.common_events.event.OrderPlacedEvent other) {
    if (other == null) {
      return new com.libms.common_events.event.OrderPlacedEvent.Builder();
    } else {
      return new com.libms.common_events.event.OrderPlacedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderPlacedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderPlacedEvent>
    implements org.apache.avro.data.RecordBuilder<OrderPlacedEvent> {

    private java.lang.CharSequence orderId;
    private java.lang.CharSequence bookName;
    private java.lang.CharSequence userEmail;
    private java.lang.CharSequence userFirstName;
    private java.lang.CharSequence userLastName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.libms.common_events.event.OrderPlacedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bookName)) {
        this.bookName = data().deepCopy(fields()[1].schema(), other.bookName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[2].schema(), other.userEmail);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userFirstName)) {
        this.userFirstName = data().deepCopy(fields()[3].schema(), other.userFirstName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.userLastName)) {
        this.userLastName = data().deepCopy(fields()[4].schema(), other.userLastName);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderPlacedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.libms.common_events.event.OrderPlacedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookName)) {
        this.bookName = data().deepCopy(fields()[1].schema(), other.bookName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userEmail)) {
        this.userEmail = data().deepCopy(fields()[2].schema(), other.userEmail);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userFirstName)) {
        this.userFirstName = data().deepCopy(fields()[3].schema(), other.userFirstName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.userLastName)) {
        this.userLastName = data().deepCopy(fields()[4].schema(), other.userLastName);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderId() {
      return orderId;
    }


    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder setOrderId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder clearOrderId() {
      orderId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookName' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookName() {
      return bookName;
    }


    /**
      * Sets the value of the 'bookName' field.
      * @param value The value of 'bookName'.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder setBookName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.bookName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bookName' field has been set.
      * @return True if the 'bookName' field has been set, false otherwise.
      */
    public boolean hasBookName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bookName' field.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder clearBookName() {
      bookName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserEmail() {
      return userEmail;
    }


    /**
      * Sets the value of the 'userEmail' field.
      * @param value The value of 'userEmail'.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder setUserEmail(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userEmail = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userEmail' field has been set.
      * @return True if the 'userEmail' field has been set, false otherwise.
      */
    public boolean hasUserEmail() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userEmail' field.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder clearUserEmail() {
      userEmail = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userFirstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserFirstName() {
      return userFirstName;
    }


    /**
      * Sets the value of the 'userFirstName' field.
      * @param value The value of 'userFirstName'.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder setUserFirstName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.userFirstName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userFirstName' field has been set.
      * @return True if the 'userFirstName' field has been set, false otherwise.
      */
    public boolean hasUserFirstName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userFirstName' field.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder clearUserFirstName() {
      userFirstName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'userLastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserLastName() {
      return userLastName;
    }


    /**
      * Sets the value of the 'userLastName' field.
      * @param value The value of 'userLastName'.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder setUserLastName(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.userLastName = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'userLastName' field has been set.
      * @return True if the 'userLastName' field has been set, false otherwise.
      */
    public boolean hasUserLastName() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'userLastName' field.
      * @return This builder.
      */
    public com.libms.common_events.event.OrderPlacedEvent.Builder clearUserLastName() {
      userLastName = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderPlacedEvent build() {
      try {
        OrderPlacedEvent record = new OrderPlacedEvent();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.bookName = fieldSetFlags()[1] ? this.bookName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userEmail = fieldSetFlags()[2] ? this.userEmail : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.userFirstName = fieldSetFlags()[3] ? this.userFirstName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.userLastName = fieldSetFlags()[4] ? this.userLastName : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderPlacedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderPlacedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderPlacedEvent>
    READER$ = (org.apache.avro.io.DatumReader<OrderPlacedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.orderId);

    out.writeString(this.bookName);

    out.writeString(this.userEmail);

    out.writeString(this.userFirstName);

    out.writeString(this.userLastName);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);

      this.bookName = in.readString(this.bookName instanceof Utf8 ? (Utf8)this.bookName : null);

      this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);

      this.userFirstName = in.readString(this.userFirstName instanceof Utf8 ? (Utf8)this.userFirstName : null);

      this.userLastName = in.readString(this.userLastName instanceof Utf8 ? (Utf8)this.userLastName : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.orderId = in.readString(this.orderId instanceof Utf8 ? (Utf8)this.orderId : null);
          break;

        case 1:
          this.bookName = in.readString(this.bookName instanceof Utf8 ? (Utf8)this.bookName : null);
          break;

        case 2:
          this.userEmail = in.readString(this.userEmail instanceof Utf8 ? (Utf8)this.userEmail : null);
          break;

        case 3:
          this.userFirstName = in.readString(this.userFirstName instanceof Utf8 ? (Utf8)this.userFirstName : null);
          break;

        case 4:
          this.userLastName = in.readString(this.userLastName instanceof Utf8 ? (Utf8)this.userLastName : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










