services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: libms-inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_inventory:/var/lib/mysql

volumes:
  mysql_data_inventory: